version: 2
jobs:
  build1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "1 hello world!!"
  build2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "2 hello world!!"
